### ISSUE TITLE
Metadata updates

### ISSUE THREAD

**Issue by ocdtrekkie** [wpsandstorm/wordpress-sandstorm#29]
Reminder on metadata currently out of date, close when resolved:

- David's email address is still the package contact. (Who is the contact for "wpsandstorm"?)
- The source code URL still goes to David's repo.

**Comment by JamborJan** [comment]
I updated the `sandstorm-pkgdef.capnp` file according to the latest default template, see https://github.com/wpsandstorm/wordpress-sandstorm/commit/80700ac09cf58957c367bb64f6a681c821438cfd.

I allowed myself to add my Keybase details as long as @xet7 and I have no other solution for publishing an app as a team rather than a individual developer.

Please feel free to reply and / or criticise this.

**Comment by ocdtrekkie** [comment]
I have no problem with this as long as xet7 is happy. I just wanted to make sure David got cleared out, as his usual request is such if someone else is taking over publishing.
